export const products = [
  {
    id_product: 1,
    name: "TV 32",
    img_product: [
      "https://hiperaudio.com.ar/wp-content/uploads/2022/06/SAMS32.png",
    ],
    description: "Tv Samsung 32 Smart",
    category: ["Tecnholgy", "Home"],
    date_creation: "2024-05-28",
    price: 200000,
    quantity: 1,
    available: true,
    average_mark: 6,
    status: "Hay stock",
    id_review: 1,
    id_discounts: 1,
    id_store: 1,
  },
  {
    id_product: 2,
    name: "Playstation 5",
    img_product: [
      "https://nextgames.com.ar/img/Public/1040/producto-ps5-slim-lectora-3327.jpg",
    ],
    description: "Videogame Console",
    category: ["Tecnholgy"],
    date_creation: "2024-05-25",
    price: 900000,
    quantity: 1,
    available: true,
    average_mark: 7,
    status: "Hay stock",
    id_review: 2,
    id_discounts: 2,
    id_store: 2,
  },
  {
    id_product: 3,
    name: "Mouse",
    img_product: [
      "https://s3-sa-east-1.amazonaws.com/saasargentina/oaPmQNJPQeMZynN9AOk5/imagen",
    ],
    description: "Hardware",
    category: ["Tecnholgy"],
    date_creation: "2024-05-23",
    price: 80000,
    quantity: 1,
    available: true,
    average_mark: 7,
    status: "Hay stock",
    id_review: 3,
    id_discounts: 3,
    id_store: 3,
  },
  {
    id_product: 4,
    name: "Speaker JBL",
    img_product: [
      "https://outtec.com.ar/wp-content/uploads/2022/01/JBLGO3REDAM-1.jpg",
    ],
    description: "Speaker waterproof",
    category: ["Tecnholgy", "Home"],
    date: "2024-05-21",
    price: 90000,
    quantity: 1,
    available: true,
    average_mark: 5,
    status: "Hay stock",
    id_review: 4,
    id_discounts: 4,
    id_store: 4,
  },
  {
    id_product: 5,
    name: "Adidas Jacket",
    img_product: [
      "https://s3.sa-east-1.amazonaws.com/www.vaypol.com.ar/variants/dh6mhvgoe8u27z8mbj78t7w23xfj/c77c2a06864ac9aca38dc5bd9371de015471edcdbf322dfb14411689bf968ae5",
    ],
    description: "Lightblue Jacket with zipper",
    category: ["Clothes"],
    date: "2024-05-21",
    price: 120000,
    quantity: 1,
    available: true,
    average_mark: 8,
    status: "Hay stock",
    id_review: 4,
    id_discounts: 4,
    id_store: 4,
  },
  {
    id_product: 6,
    name: "Iphone 13",
    img_product: [
      "https://tienda.personal.com.ar/images/720/webp/i_Phone_13_Pro_256_GB_Graphite_73f3e06d1c.png",
    ],
    description: "Cellphone Iphone 13",
    category: ["Smartphones"],
    date: "2024-05-25",
    price: 1200000,
    quantity: 1,
    available: true,
    average_mark: 8,
    status: "Hay stock",
    id_review: 4,
    id_discounts: 4,
    id_store: 4,
  },
  {
    id_product: 7,
    name: "Adidas Forum",
    img_product: [
      "https://newsport.vtexassets.com/arquivos/ids/18415556-800-auto?v=638398790520200000&width=800&height=auto&aspect=true",
    ],
    description: "Sneackers color green and white",
    category: ["Clothes"],
    date: "2024-05-25",
    price: 300000,
    quantity: 1,
    available: true,
    average_mark: 8,
    status: "Hay stock",
    id_review: 4,
    id_discounts: 4,
    id_store: 4,
  },
  {
    id_product: 8,
    name: "S23 Ultra",
    img_product: [
      "https://d22fxaf9t8d39k.cloudfront.net/40c63b88178435f76d173b03430fb849743ac10b6d857260f591168815f36cd3155135.jpg",
    ],
    description: "Samsung phone S23 ultra",
    category: ["Smartphones"],
    date: "2024-05-21",
    price: 1000000,
    quantity: 1,
    available: true,
    average_mark: 7,
    status: "Hay stock",
    id_review: 4,
    id_discounts: 4,
    id_store: 4,
  },
];

export const store = [
  {
    id: 1,
    name: "Tech Haven",
    address_cp: "90210",
    address_country: "USA",
    address_city: "Beverly Hills",
    logo: "https://i.pinimg.com/originals/d9/bb/48/d9bb48c52123cd7b1304979b7c6cb9bc.jpg"
  },
  {
    id: 2,
    name: "Gadget World",
    address_cp: "10001",
    address_country: "USA",
    address_city: "New York",
    logo: "https://marketplace.canva.com/EAFAEOunkG0/1/0/1600w/canva-morado-moderno-tecnolog%C3%ADa-y-videojuegos-logo-2xfRaIEdz2Y.jpg"
  },
  {
    id: 3,
    name: "Fashion Hub",
    address_cp: "WC2N 5DU",
    address_country: "UK",
    address_city: "London",
    logo: "https://w7.pngwing.com/pngs/617/346/png-transparent-circle-logo-brand-ibm-text-logo-technology.png"
  },
  {
    id: 4,
    name: "Eco Mart",
    address_cp: "75001",
    address_country: "France",
    address_city: "Paris",
    logo: "https://www.designevo.com/res/templates/thumb_small/tech-square-line-structure-crypto.webp"
  },
]
