module.exports = [
  {
    address_cp: "12345",
    address_country: "Argentina",
    address_city: "Buenos Aires",
    name: "Ferreteria Lopez",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReWtdna4NlKIKF08Y50ejW_B6LSexwXHLtrQ&s",
  },
  {
    address_cp: "54321",
    address_country: "Argentina",
    address_city: "Córdoba",
    name: "Ferreteria Martinez",
    logo: "https://st2.depositphotos.com/4335005/7939/v/450/depositphotos_79399298-stock-illustration-vector-flat-icon.jpg",
  },
  {
    address_cp: "54321",
    address_country: "Argentina",
    address_city: "Córdoba",
    name: "Falabella",
    logo: "https://images.falabella.com/v3/assets/blt7c5c2f2f888a7cc3/blt09274da39e1b6410/622b895af26a4b66ea4a1452/iconos-CDA-Horarios-Falabella-V1.png",
  },
  {
    address_cp: "54321",
    address_country: "Argentina",
    address_city: "Córdoba",
    name: "Musimundo",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0i9pRS28qXlxeUdrx2Rd16ByN5hHUvnpirw&s",
  },
  {
    address_cp: "54322",
    address_country: "Argentina",
    address_city: "Misiones",
    name: "Fravega",
    logo: "https://assets.hotsale.com.ar/uploads/brands/14464/orig-1713499149-fravega.jpg",
  },
  {
    address_cp: "54311",
    address_country: "Argentina",
    address_city: "Salta",
    name: "CompraGamer",
    logo: "https://i.ibb.co/wzwdDbs/313413301-552706986663673-2669822241094639465-n.jpg",
  },
  {
    address_cp: "9000",
    address_country: "Argentina",
    address_city: "CABA",
    name: "Montagne",
    logo: "https://d368r8jqz0fwvm.cloudfront.net/themes/mtg2018/img/montagne-logo.svg",
  },
  {
    address_cp: "1430",
    address_country: "Argentina",
    address_city: "CABA",
    name: "Garbarino",
    logo: "https://cdn.webpushr.com/siteassets/v9gXmgAzrZ.jpeg",
  },
  {
    address_cp: "1619",
    address_country: "Argentina",
    address_city: "Vicente López",
    name: "Disco",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Disco-Supermarket-Logo.svg/640px-Disco-Supermarket-Logo.svg.png",
  },
  {
    address_cp: "7600",
    address_country: "Argentina",
    address_city: "Mar del Plata",
    name: "La Anónima",
    logo: "https://play-lh.googleusercontent.com/_a3LDMzVn4F20gUzHzRZcuv0rZb-lTlQWkzpTquzsplFqZPK_K-YouA9y5hn3rcKsA",
  },
  {
    address_cp: "1405",
    address_country: "Argentina",
    address_city: "CABA",
    name: "Coto",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ83TZueWvV__ZN-a6XCiA1j_RYWLnlnf_liA&s",
  },
  {
    address_cp: "1417",
    address_country: "Argentina",
    address_city: "CABA",
    name: "Naldo Lombardi",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPRfHhQtoNLFmLJQhDBwbeyrjChwUmFRJUFA&s",
  },
];
